name: Add ReviewNeeded Label

on:
  workflow_call:

jobs:
  label_review_needed:
    runs-on: actions-runner
    permissions:
      pull-requests: write
      repository-projects: read
    steps:
      - name: Add ReviewNeeded Label to Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ReviewNeeded']
            })
