name: Add ReviewNeeded Label to opened issue
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GH_TOKEN:
        required: true
    inputs:
      MEMBER_LIST:
        description: 'github_id:slack_idのカンマ区切り文字列'
        required: true
        type: string

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  label_review_needed:
    uses: harvest-development/.github/.github/workflows/add-review-label.yml@main
  send_issues:
    runs-on: actions-runner
    steps:
    - name: レビューア情報の取得とメッセージ作成
      uses: actions/github-script@v7
      id: label_and_create_message
      env:
        MEMBER_LIST: ${{ inputs.MEMBER_LIST }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          const memberList = process.env.MEMBER_LIST.split(',');
          const reviewers = context.payload.pull_request.requested_reviewers.map(r => r.login);
          let notifyList = [];
          let message = '';

          if (reviewers.length === 0 ) {
            throw new Error('レビューアが設定されていません。');
          }

          // GitHub ID と Slack ID の対応付けを行う
          reviewers.forEach(reviewer => {
            memberList.forEach(member => {
              const [githubId, slackId] = member.split(':');
              if (githubId === reviewer) {
                notifyList.push(`<${slackId}>`);
              }
            });
          });

          if (notifyList.length > 0) {
            const prUrl = context.payload.pull_request.html_url;
            const prNumber = context.payload.pull_request.number;

            const message = `プルリクエスト <${prUrl}|#${prNumber}> が${context.payload.action === 'edited' ? '変更': '作成'}されました。 Reviewer: ${notifyList.join(', ')}`;

            // Slack通知のためにメッセージをエコー
            console.log(`Slackメッセージ: ${message}`);
            return message
          } else {
            throw new Error(`レビュアーのSlack IDが設定されていません。 レビュアー: ${reviewers}`);
          }
    - name: Slack通知の送信
      uses: slackapi/slack-github-action@v1.27.0
      if: steps.label_and_create_message.outputs.result
      with:
        payload: |
          {
            "text": "${{ steps.label_and_create_message.outputs.result }}",
            "blocks": [],
            "attachments": []
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

